language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jnsbr/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jnsbr/docker-react npm run test